// Self-hosts the site's typefaces so no third-party font request is made.
//
// Choices are deliberately British: Libre Caslon Text after William Caslon
// (London, 1720s), Libre Baskerville after John Baskerville (Birmingham,
// 1750s), and Cabin, a humanist sans in the Edward Johnston / Eric Gill
// lineage that gave us the London Underground and Gill Sans letterforms.
import fs from 'node:fs';
import path from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';

const FAMILIES = [
  'Libre+Caslon+Text:ital,wght@0,400;0,700;1,400',
  'Libre+Baskerville:wght@700',
  'Cabin:wght@400;500;600',
];

const OUT_DIR = 'public/fonts';
fs.mkdirSync(OUT_DIR, { recursive: true });

let css = '';
for (const fam of FAMILIES) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${fam}&display=swap`, {
    headers: { 'User-Agent': UA },
  });
  css += (await res.text()) + '\n';
}

const urls = [...new Set(css.match(/https:\/\/[^)]*\.woff2/g) ?? [])];
let total = 0;

for (const [i, url] of urls.entries()) {
  const family = url.split('/s/')[1].split('/')[0];
  const name = `${family}-${i + 1}.woff2`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(path.join(OUT_DIR, name), buf);
  total += buf.length;
  css = css.split(url).join(`/fonts/${name}`);
}

fs.writeFileSync(
  'src/styles/fonts.css',
  '/* Generated by scripts/fetch-fonts.mjs — self-hosted, no third-party requests. */\n' + css
);

console.log(`${urls.length} files, ${Math.round(total / 1024)} KB total`);
